quarkiverse/quarkus-amazon-services

- common/deployment/src/main/java/io/quarkus/amazon/common/deployment/AbstractAmazonServiceProcessor.java
- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AmazonClientRecorder.java
- dynamodb/deployment/src/main/java/io/quarkus/amazon/dynamodb/deployment/DynamodbProcessor.java
- iam/deployment/src/main/java/io/quarkus/amazon/iam/deployment/IamProcessor.java
- integration-tests/src/main/java/io/quarkus/it/amazon/s3/S3Resource.java
- integration-tests/src/test/java/io/quarkus/it/amazon/AmazonS3Test.java
- kms/deployment/src/main/java/io/quarkus/amazon/kms/deployment/KmsProcessor.java
- s3/deployment/src/main/java/io/quarkus/amazon/s3/deployment/S3Processor.java
- s3/runtime/src/main/java/io/quarkus/amazon/s3/runtime/S3ClientProducer.java
- s3/runtime/src/main/java/io/quarkus/amazon/s3/runtime/S3Recorder.java
- secretsmanager/deployment/src/main/java/io/quarkus/amazon/secretsmanager/deployment/SecretsManagerProcessor.java
- ses/deployment/src/main/java/io/quarkus/amazon/ses/deployment/SesProcessor.java
- sns/deployment/src/main/java/io/quarkus/amazon/sns/deployment/SnsProcessor.java
- sqs/deployment/src/main/java/io/quarkus/amazon/sqs/deployment/SqsProcessor.java
- ssm/deployment/src/main/java/io/quarkus/amazon/ssm/deployment/SsmProcessor.java
Uses the S3 configuration to produce an `S3Presigner` bean.
> Produce configured S3Presigner bean

- common/deployment/src/main/java/io/quarkus/amazon/common/deployment/AmazonServicesClientsProcessor.java
> Use java.util.function.Predicate instead of Google Common one

- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AwsCredentialsProviderConfig.java
- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AwsCredentialsProviderType.java
- docs/modules/ROOT/pages/includes/quarkus-amazon-dynamodb.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-iam.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-kms.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-s3.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-secretsmanager.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-ses.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sns.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sqs.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-ssm.adoc
adds a convenient way to use SSO credentials directly in the app config
> add ability to statically configure session token

- cognito-user-pools/runtime/src/main/java/io/quarkus/amazon/cognitouserpools/runtime/CognitoUserPoolsRecorder.java
aligns the new recorder for cognito user pools with #108
> update cognito-user-pools to support #108

- docs/modules/ROOT/pages/amazon-dynamodb.adoc
- docs/modules/ROOT/pages/amazon-kms.adoc
- docs/modules/ROOT/pages/amazon-s3.adoc
- docs/modules/ROOT/pages/amazon-secretsmanager.adoc
- docs/modules/ROOT/pages/amazon-ses.adoc
- docs/modules/ROOT/pages/amazon-sns.adoc
- docs/modules/ROOT/pages/amazon-sqs.adoc
- docs/modules/ROOT/pages/amazon-ssm.adoc
issue https://github.com/quarkiverse/quarkus-amazon-services/issues/246
> Update DynamoDB Docs, replaced shell with aws cli command

- docs/modules/ROOT/pages/amazon-dynamodb.adoc
Add paragraph about enhanced client
> Update dynamo db docs

- common/deployment/src/main/java/io/quarkus/amazon/common/deployment/DevServicesLocalStackProcessor.java
- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/DevServicesBuildTimeConfig.java
- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/LocalStackDevServicesBuildTimeConfig.java
- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/MotoDevServicesBuildTimeConfig.java
- docs/modules/ROOT/pages/amazon-cognitouserpools.adoc
- docs/modules/ROOT/pages/amazon-dynamodb.adoc
- docs/modules/ROOT/pages/amazon-kms.adoc
- docs/modules/ROOT/pages/amazon-s3.adoc
- docs/modules/ROOT/pages/amazon-secretsmanager.adoc
- docs/modules/ROOT/pages/amazon-ses.adoc
- docs/modules/ROOT/pages/amazon-sns.adoc
- docs/modules/ROOT/pages/amazon-sqs.adoc
- docs/modules/ROOT/pages/amazon-ssm.adoc
- docs/modules/ROOT/pages/dev-services.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-cognitouserpools.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-dynamodb.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-iam.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-kms.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-s3.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-secretsmanager.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-ses.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sns.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sqs.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-ssm.adoc
Add some documentation
Refs: #253
> Devservices documentation

- cognito-user-pools/runtime/src/main/java/io/quarkus/amazon/cognitouserpools/runtime/CognitoUserPoolsClientProducer.java
- dynamodb-enhanced/runtime/src/main/java/io/quarkus/amazon/dynamodb/enhanced/runtime/DynamodbEnhancedClientProducer.java
- dynamodb/runtime/src/main/java/io/quarkus/amazon/dynamodb/runtime/DynamodbClientProducer.java
- iam/runtime/src/main/java/io/quarkus/amazon/iam/runtime/IamClientProducer.java
- kms/runtime/src/main/java/io/quarkus/amazon/kms/runtime/KmsClientProducer.java
- s3/runtime/src/main/java/io/quarkus/amazon/s3/runtime/S3ClientProducer.java
- secretsmanager/runtime/src/main/java/io/quarkus/amazon/secretsmanager/runtime/SecretsManagerClientProducer.java
- ses/runtime/src/main/java/io/quarkus/amazon/ses/runtime/SesClientProducer.java
- sns/runtime/src/main/java/io/quarkus/amazon/sns/runtime/SnsClientProducer.java
- sqs/runtime/src/main/java/io/quarkus/amazon/sqs/runtime/SqsClientProducer.java
- ssm/runtime/src/main/java/io/quarkus/amazon/ssm/runtime/SsmClientProducer.java
> #330 mark default amazon clients producers as DefaultBean

- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AwsCredentialsProviderConfig.java
- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AwsCredentialsProviderType.java
- docs/modules/ROOT/pages/includes/quarkus-amazon-cognitouserpools.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-dynamodb.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-iam.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-kms.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-s3.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-secretsmanager.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-ses.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sns.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sqs.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-ssm.adoc
- s3/deployment/src/test/java/io/quarkus/amazon/s3/deployment/S3CustomCredentialsProviderMissedBeanNameTest.java
- s3/deployment/src/test/java/io/quarkus/amazon/s3/deployment/S3CustomCredentialsProviderMissedBeanTest.java
- s3/deployment/src/test/java/io/quarkus/amazon/s3/deployment/S3CustomCredentialsProviderTest.java
- s3/deployment/src/test/resources/custom-credentials-provider-missed-bean.properties
- s3/deployment/src/test/resources/custom-credentials-provider-missed-name.properties
- s3/deployment/src/test/resources/custom-credentials-provider.properties
> #332 allow using custom credentials provider

- common/deployment/src/main/java/io/quarkus/amazon/common/deployment/DevServicesLocalStackProcessor.java
- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/LocalStackDevServicesBuildTimeConfig.java
- dynamodb/deployment/src/test/java/io/quarkus/amazon/dynamodb/deployment/InitTest.java
- dynamodb/deployment/src/test/resources/localstack-init-script-config.properties
- dynamodb/deployment/src/test/resources/localstack-init/01_configure_cli.sh
- dynamodb/deployment/src/test/resources/localstack-init/02_create_table.sh
> #303 Provide a way to use localstack init scripts

- common/deployment-spi/pom.xml
- common/deployment/src/main/java/io/quarkus/amazon/common/deployment/DevServicesAdditionalServicesLocalStackServiceProcessor.java
- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/LocalStackDevServicesBuildTimeConfig.java
- docs/modules/ROOT/pages/dev-services.adoc
- docs/modules/ROOT/pages/includes/attributes.adoc
- integration-tests/src/main/java/io/quarkus/it/amazon/localstack/RedshiftResource.java
- integration-tests/src/main/resources/application.properties
- integration-tests/src/test/java/io/quarkus/it/amazon/AmazonLocalStackTest.java
Refs: https://github.com/quarkiverse/quarkus-amazon-services/issues/370
> Allow to start additional localstack services for dev services

- common/deployment-spi/src/main/java/io/quarkus/amazon/common/deployment/spi/AbstractDevServicesLocalStackProcessor.java
- devservices/s3/src/main/java/io/quarkus/amazon/devservices/s3/S3DevServicesProcessor.java
- integration-tests/src/main/resources/application.properties
https://github.com/quarkiverse/quarkus-amazon-services/issues/483
> Force s3 client configured with devservice to use path-style addressing

- integration-tests/src/main/java/io/quarkus/it/amazon/ssm/SsmResource.java
localstack v2 will faill the test if path do not start with /
> Fix ssm test to be compatible with localstack v2

- devservices/sqs/pom.xml
- devservices/sqs/src/main/java/io/quarkus/amazon/devservices/sqs/SqsDevServicesProcessor.java
- docs/modules/ROOT/pages/amazon-sqs.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sqs.adoc
- sqs/deployment/src/test/java/io/quarkus/amazon/sqs/deployment/SqsDevServicesWithSimpleQueuesTest.java
- sqs/deployment/src/test/java/io/quarkus/amazon/sqs/deployment/SqsDevServicesWithoutQueueTest.java
- sqs/runtime/src/main/java/io/quarkus/amazon/sqs/runtime/SqsBuildTimeConfig.java
- sqs/runtime/src/main/java/io/quarkus/amazon/sqs/runtime/SqsDevServicesBuildTimeConfig.java
Fix https://github.com/quarkiverse/quarkus-amazon-services/issues/565
> Allow SQS queue creation on devservices startup

- common/deployment/src/main/java/io/quarkus/amazon/common/deployment/DevServicesLocalStackProcessor.java
> Detect docker availability only if a container should be started

- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/DevServicesBuildTimeConfig.java
- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/MotoDevServicesBuildTimeConfig.java
- docs/modules/ROOT/pages/dev-services.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-cognitouserpools.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-dynamodb.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-iam.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-kms.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-s3.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-secretsmanager.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-ses.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sns.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sqs.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-ssm.adoc
- docs/modules/ROOT/pages/includes/quarkus-aws-devservices-localstack-local-stack-dev-services-build-time-config.adoc
- docs/modules/ROOT/pages/includes/quarkus-aws-devservices-moto-moto-dev-services-build-time-config.adoc
- docs/pom.xml
Fixes https://github.com/quarkiverse/quarkus-amazon-services/issues/680
> Add dev services config reference to documentation

- bom/pom.xml
- devservices/pom.xml
- devservices/sts/pom.xml
- devservices/sts/src/main/java/io/quarkus/amazon/devservices/sts/StsDevServicesProcessor.java
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/amazon-sts.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sts.adoc
- docs/pom.xml
- integration-tests/pom.xml
- integration-tests/src/main/java/io/quarkus/it/amazon/sts/StsResource.java
- integration-tests/src/test/java/io/quarkus/it/amazon/AmazonStsITCase.java
- integration-tests/src/test/java/io/quarkus/it/amazon/AmazonStsTest.java
- pom.xml
- sts/deployment/pom.xml
- sts/deployment/src/main/java/io/quarkus/amazon/sts/deployment/StsProcessor.java
- sts/deployment/src/test/java/io/quarkus/amazon/sts/deployment/StsSyncClientFullConfigTest.java
- sts/deployment/src/test/resources/full-config.properties
- sts/pom.xml
- sts/runtime/pom.xml
- sts/runtime/src/main/java/io/quarkus/amazon/sts/runtime/StsBuildTimeConfig.java
- sts/runtime/src/main/java/io/quarkus/amazon/sts/runtime/StsClientProducer.java
- sts/runtime/src/main/java/io/quarkus/amazon/sts/runtime/StsConfig.java
- sts/runtime/src/main/java/io/quarkus/amazon/sts/runtime/StsRecorder.java
- sts/runtime/src/main/java/io/quarkus/amazon/sts/runtime/StsSubstitutions.java
- sts/runtime/src/main/resources/META-INF/quarkus-extension.yaml
I wanted to finish [nicolas-vivot](https://github.com/nicolas-vivot) work from https://github.com/quarkiverse/quarkus-amazon-services/pull/30
Not sure I did everything right. 
I forked initial PR and rebased it onto main branch.
Adjusted changeset according to current quarkus version.
Enabled dev services.
Added integration tests.
Documentation is not yet done. I've linked the sts module in _docs/pom.xml_ but not sure what should be done next.
As I understand, we should have files
_docs/modules/ROOT/pages/amazon-sts.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-ssm.adoc_
but not sure, should I write them from scratch, or should I use some template, or they should be somehow (partly) generated from sources?
> #30 updated, added integration tests and dev services

- common/deployment/src/main/java/io/quarkus/amazon/common/deployment/AmazonServicesClientsProcessor.java
`url-connection-client` is imported by devservices. The actual test detects its presence in the global classpath instead of just the runtime classpath.
> Throw exception if url-connection-client is needed and missing

- common/deployment/pom.xml
- common/deployment/src/main/java/io/quarkus/amazon/common/deployment/AmazonServicesClientsProcessor.java
- docs/modules/ROOT/pages/includes/attributes.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-cognitouserpools.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-dynamodb.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-iam.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-kms.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-s3.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-secretsmanager.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-ses.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sns.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sqs.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-ssm.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sts.adoc
- integration-tests/pom.xml
- pom.xml
Fix #637 and a few deprecated method calls
> Refactor code to Quarkus 3.1

- cognito-user-pools/deployment/src/main/java/io/quarkus/amazon/cognitouserpools/deployment/CognitoUserPoolsProcessor.java
- common/deployment/src/main/java/io/quarkus/amazon/common/deployment/AbstractAmazonServiceProcessor.java
- dynamodb/deployment/src/main/java/io/quarkus/amazon/dynamodb/deployment/DynamodbProcessor.java
- iam/deployment/src/main/java/io/quarkus/amazon/iam/deployment/IamProcessor.java
- kms/deployment/src/main/java/io/quarkus/amazon/kms/deployment/KmsProcessor.java
- s3/deployment/src/main/java/io/quarkus/amazon/s3/deployment/S3Processor.java
- secretsmanager/deployment/src/main/java/io/quarkus/amazon/secretsmanager/deployment/SecretsManagerProcessor.java
- ses/deployment/src/main/java/io/quarkus/amazon/ses/deployment/SesProcessor.java
- sns/deployment/src/main/java/io/quarkus/amazon/sns/deployment/SnsProcessor.java
- sqs/deployment/src/main/java/io/quarkus/amazon/sqs/deployment/SqsProcessor.java
- ssm/deployment/src/main/java/io/quarkus/amazon/ssm/deployment/SsmProcessor.java
- sts/deployment/src/main/java/io/quarkus/amazon/sts/deployment/StsProcessor.java
Fix build steps cycle with quarkus cxf.
https://github.com/quarkiverse/quarkus-cxf/issues/860
> refactor: split build steps to reduce cycles issues with other extensions

- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AmazonClientNettyTransportRecorder.java
- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/NettyHttpClientConfig.java
> fix: remove usage of netty in config classes

- common/deployment/src/main/java/io/quarkus/amazon/common/deployment/AbstractAmazonServiceProcessor.java
- docs/modules/ROOT/pages/amazon-dynamodb.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-dynamodb-enhanced.adoc
- dynamodb-enhanced/deployment/pom.xml
- dynamodb-enhanced/deployment/src/main/java/io/quarkus/amazon/dynamodb/enhanced/deployment/DotNames.java
- dynamodb-enhanced/deployment/src/main/java/io/quarkus/amazon/dynamodb/enhanced/deployment/DynamodbEnhancedDbTableProcessor.java
- dynamodb-enhanced/deployment/src/main/java/io/quarkus/amazon/dynamodb/enhanced/deployment/DynamodbEnhancedProcessor.java
- dynamodb-enhanced/deployment/src/main/java/io/quarkus/amazon/dynamodb/enhanced/deployment/DynamodbEnhancedTableBuildItem.java
- dynamodb-enhanced/deployment/src/test/java/io/quarkus/amazon/dynamodb/enhanced/deployment/DynamoDBExampleTableEntry.java
- dynamodb-enhanced/deployment/src/test/java/io/quarkus/amazon/dynamodb/enhanced/deployment/DynamoDBExampleTableNotABean.java
- dynamodb-enhanced/deployment/src/test/java/io/quarkus/amazon/dynamodb/enhanced/deployment/DynamoDbEnhancedDbTableNotABeanTest.java
- dynamodb-enhanced/deployment/src/test/java/io/quarkus/amazon/dynamodb/enhanced/deployment/DynamoDbEnhancedDbTableTest.java
- dynamodb-enhanced/deployment/src/test/resources/full-config.properties
- dynamodb-enhanced/runtime/src/main/java/io/quarkus/amazon/dynamodb/enhanced/runtime/DynamoDbEnhancedBuildTimeConfig.java
- dynamodb-enhanced/runtime/src/main/java/io/quarkus/amazon/dynamodb/enhanced/runtime/NamedDynamoDbTable.java
- integration-tests/pom.xml
- integration-tests/src/main/java/io/quarkus/it/amazon/dynamodb/enhanced/BaseDynamoDbBean.java
- integration-tests/src/main/java/io/quarkus/it/amazon/dynamodb/enhanced/DynamoDBExampleTableEntry.java
- integration-tests/src/main/java/io/quarkus/it/amazon/dynamodb/enhanced/DynamoDbEnhancedAbstractResource.java
- integration-tests/src/main/java/io/quarkus/it/amazon/dynamodb/enhanced/DynamoDbEnhancedDbTableResource.java
- integration-tests/src/main/java/io/quarkus/it/amazon/dynamodb/enhanced/DynamoDbEnhancedResource.java
- integration-tests/src/test/java/io/quarkus/it/amazon/AmazonDynamoDBEnhancedTest.java
> feat: inject DynamoDbTable and DynamoDbAsyncTable

- docs/modules/ROOT/pages/includes/attributes.adoc
- s3/runtime/pom.xml
- s3/runtime/src/main/java/io/quarkus/amazon/s3/runtime/S3CrtSubstitutions.java
> fix: fix native build of s3 when aws-crt is not present

- dynamodb-enhanced/deployment/src/main/java/io/quarkus/amazon/dynamodb/enhanced/deployment/DynamodbEnhancedProcessor.java
- dynamodb-enhanced/deployment/src/test/java/io/quarkus/amazon/dynamodb/enhanced/deployment/DynamoDbEnhancedClientAllowOverrideWithProducerTest.java
- dynamodb-enhanced/deployment/src/test/java/io/quarkus/amazon/dynamodb/enhanced/deployment/DynamoDbEnhancedClientProducer.java
> fix: add defaultBean qualifier for DynamoDbEnhancedClient synthetic beans

- docs/antora.yml
> docs: separate docs for for 2.4 branch

- common/deployment/src/main/java/io/quarkus/amazon/common/deployment/AbstractAmazonServiceProcessor.java
- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AmazonClientCommonRecorder.java
- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/SdkConfig.java
- docs/modules/ROOT/pages/includes/quarkus-amazon-cognitouserpools.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-dynamodb-enhanced.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-dynamodb.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-iam.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-kms.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-s3.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-secretsmanager.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-ses.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sns.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sqs.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-ssm.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sts.adoc
- docs/modules/ROOT/pages/includes/quarkus-aws-devservices-localstack-local-stack-dev-services-build-time-config.adoc
- docs/modules/ROOT/pages/includes/quarkus-aws-devservices-moto-moto-dev-services-build-time-config.adoc
> feat: add config option to disable Quarkus thread pool usage

- docs/modules/ROOT/pages/dev-services.adoc
> docs: Add guidance for handling Docker support in test mode

- common/runtime/pom.xml
- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/CrtSubstitutions.java
- pom.xml
> fix: support awssdk version 2.21.0 in native build

- README.md
- bom/pom.xml
- common/deployment-devservices-spi/src/main/java/io/quarkus/amazon/common/deployment/spi/AbstractDevServicesLocalStackProcessor.java
- devservices/eventbridge/pom.xml
- devservices/eventbridge/src/main/java/io/quarkus/amazon/devservices/eventbridge/EventBridgeDevServicesProcessor.java
- devservices/pom.xml
- docs/modules/ROOT/pages/amazon-eventbridge.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-eventbridge.adoc
- docs/pom.xml
- eventbridge/deployment/pom.xml
- eventbridge/deployment/src/main/java/io/quarkus/amazon/eventbridge/deployment/EventBridgeProcessor.java
- eventbridge/deployment/src/test/java/io/quarkus/amazon/eventbridge/deployment/EventBridgeSyncClientFullConfigTest.java
- eventbridge/deployment/src/test/resources/full-config.properties
- eventbridge/pom.xml
- eventbridge/runtime/pom.xml
- eventbridge/runtime/src/main/java/io/quarkus/amazon/eventbridge/runtime/EventBridgeBuildTimeConfig.java
- eventbridge/runtime/src/main/java/io/quarkus/amazon/eventbridge/runtime/EventBridgeClientProducer.java
- eventbridge/runtime/src/main/java/io/quarkus/amazon/eventbridge/runtime/EventBridgeConfig.java
- eventbridge/runtime/src/main/java/io/quarkus/amazon/eventbridge/runtime/EventBridgeRecorder.java
- eventbridge/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- integration-tests/pom.xml
- integration-tests/src/main/java/io/quarkus/it/amazon/eventbridge/EventBridgeResource.java
- integration-tests/src/main/resources/application.properties
- integration-tests/src/test/java/io/quarkus/it/amazon/AmazonEventBridgeITCase.java
- integration-tests/src/test/java/io/quarkus/it/amazon/AmazonEventBridgeTest.java
- pom.xml
> feat: add support for eventbridge client

- crt/deployment/src/main/java/io/quarkiverse/amazonservices/aws/crt/deployment/AwsCrtProcessor.java
> fix: declare dynamically resolve CrtRuntimeException ctor

- common/deployment/src/main/java/io/quarkus/amazon/common/deployment/AbstractAmazonServiceProcessor.java
- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/SdkAutoCloseableDestroyer.java
- docs/modules/ROOT/pages/amazon-s3.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-s3.adoc
- integration-tests/src/main/java/io/quarkus/it/amazon/s3/S3Resource.java
- integration-tests/src/test/java/io/quarkus/it/amazon/AmazonS3Test.java
- s3/deployment/src/main/java/io/quarkus/amazon/s3/deployment/S3CrtProcessor.java
- s3/runtime/src/main/java/io/quarkus/amazon/s3/runtime/S3Config.java
- s3/runtime/src/main/java/io/quarkus/amazon/s3/runtime/S3Crt.java
- s3/runtime/src/main/java/io/quarkus/amazon/s3/runtime/S3CrtConfig.java
- s3/runtime/src/main/java/io/quarkus/amazon/s3/runtime/S3CrtRecorder.java
- s3/runtime/src/main/java/io/quarkus/amazon/s3/runtime/S3CrtSubstitutions.java
> feat: add support for s3 crt client

- crt/deployment/src/main/java/io/quarkiverse/amazonservices/aws/crt/deployment/AwsCrtProcessor.java
> fix: runtime initialized types dependent on CRT

- README.md
> doc: clarify compatibility matrix with quarkus

- common/deployment/src/main/java/io/quarkus/amazon/common/deployment/AmazonServicesClientsProcessor.java
- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AmazonClientCommonRecorder.java
- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/SdkBuildTimeConfig.java
- docs/modules/ROOT/pages/includes/quarkus-amazon-cognitouserpools.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-dynamodb.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-eventbridge.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-iam.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-kinesis.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-kms.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-lambda.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-s3.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-secretsmanager.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-ses.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sfn.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sns.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sqs.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-ssm.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sts.adoc
- integration-tests/src/main/java/io/quarkus/it/amazon/s3/S3ModifyResponse.java
- integration-tests/src/main/java/io/quarkus/it/amazon/s3/S3ModifyResponseProducer.java
> feat: try to resolve interceptors from CDI first

- bom/pom.xml
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/amazon-s3.adoc
- integration-tests/pom.xml
- integration-tests/src/main/java/io/quarkus/it/amazon/s3/S3Resource.java
- integration-tests/src/main/java/io/quarkus/it/amazon/s3transfermanager/S3TransferManagerResource.java
- integration-tests/src/main/java/io/quarkus/it/amazon/s3transfermanager/S3TransferManagerUtils.java
- integration-tests/src/test/java/io/quarkus/it/amazon/AmazonS3Test.java
- pom.xml
- s3-transfer-manager/deployment/pom.xml
- s3-transfer-manager/deployment/src/main/java/io/quarkus/amazon/s3/deployment/S3TransferManagerProcessor.java
- s3-transfer-manager/deployment/src/test/java/io/quarkus/amazon/s3/deployment/S3TransferManagerClientFullConfigTest.java
- s3-transfer-manager/deployment/src/test/resources/sync-urlconn-full-config.properties
- s3-transfer-manager/pom.xml
- s3-transfer-manager/runtime/pom.xml
- s3-transfer-manager/runtime/src/main/java/io/quarkus/amazon/s3/runtime/S3CrtTransferManagerRecorder.java
- s3-transfer-manager/runtime/src/main/java/io/quarkus/amazon/s3/runtime/S3CrtTransferManagerSubstitutions.java
- s3-transfer-manager/runtime/src/main/java/io/quarkus/amazon/s3/runtime/S3TransferManagerProducer.java
- s3-transfer-manager/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- s3/deployment/src/main/java/io/quarkus/amazon/s3/deployment/S3CrtProcessor.java
> feat: add support for s3TransferManager

- common/deployment-devservices-spi/src/main/java/io/quarkus/amazon/common/deployment/spi/AbstractDevServicesLocalStackProcessor.java
- common/deployment-devservices-spi/src/main/java/io/quarkus/amazon/common/deployment/spi/LocalStackDevServicesBaseConfig.java
- common/deployment/src/main/java/io/quarkus/amazon/common/deployment/DevServicesLocalStackProcessor.java
- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/DevServicesBuildTimeConfig.java
- devservices/s3/src/main/java/io/quarkus/amazon/devservices/s3/S3DevServicesProcessor.java
- devservices/sqs/src/main/java/io/quarkus/amazon/devservices/sqs/SqsDevServicesProcessor.java
- docs/modules/ROOT/pages/dev-services.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-cognitouserpools.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-dynamodb.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-eventbridge.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-iam.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-kinesis.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-kms.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-lambda.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-s3.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-secretsmanager.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-ses.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sfn.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sns.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sqs.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-ssm.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sts.adoc
- docs/modules/ROOT/pages/includes/quarkus-aws-devservices-localstack-local-stack-dev-services-build-time-config.adoc
> feat: allow to group shared dev services

- common/runtime/pom.xml
- dynamodb-enhanced/runtime/pom.xml
- s3-transfer-manager/runtime/pom.xml
- s3/runtime/pom.xml
- sts/runtime/pom.xml
> fix: use org.graalvm.sdk:nativeimage

- docs/modules/ROOT/pages/includes/quarkus-amazon-s3.adoc
- s3/runtime/src/main/java/io/quarkus/amazon/s3/runtime/S3CrtConfig.java
- s3/runtime/src/main/java/io/quarkus/amazon/s3/runtime/S3CrtRecorder.java
> feat: add maxNativeMemoryLimitInBytes configuration option to the S3Client

- common/deployment/src/main/java/io/quarkus/amazon/common/deployment/AbstractAmazonServiceProcessor.java
- common/runtime/src/main/java/io/quarkus/amazon/common/runtime/OtelSubstitutions.java
> feat: add native substitutions for otel

- devservices/sqs/src/main/java/io/quarkus/amazon/devservices/sqs/SqsDevServicesProcessor.java
Hi Team,
I am not sure, but I think this is a typo.
> fix: Service in devservices

- README.md
- bom/pom.xml
- devservices/ecr/pom.xml
- devservices/ecr/src/main/java/io/quarkus/amazon/devservices/ecr/EcrDevServicesProcessor.java
- devservices/pom.xml
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/amazon-ecr.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-cloudwatch.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-ecr.adoc
- docs/pom.xml
- ecr/deployment/pom.xml
- ecr/deployment/src/main/java/io/quarkus/amazon/ecr/deployment/EcrProcessor.java
- ecr/deployment/src/test/java/io/quarkus/amazon/ecr/deployment/EcrDevServicesTest.java
- ecr/deployment/src/test/java/io/quarkus/amazon/ecr/deployment/EcrSyncClientFullConfigTest.java
- ecr/deployment/src/test/resources/sync-urlconn-full-config.properties
- ecr/pom.xml
- ecr/runtime/pom.xml
- ecr/runtime/src/main/java/io/quarkus/amazon/ecr/runtime/EcrBuildTimeConfig.java
- ecr/runtime/src/main/java/io/quarkus/amazon/ecr/runtime/EcrClientProducer.java
- ecr/runtime/src/main/java/io/quarkus/amazon/ecr/runtime/EcrConfig.java
- ecr/runtime/src/main/java/io/quarkus/amazon/ecr/runtime/EcrRecorder.java
- ecr/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- pom.xml
> Support for the ECR client #1371

- apigatewaymanagementapi/deployment/src/main/java/io/quarkiverse/amazon/apigatewaymanagementapi/deployment/ApiGatewayManagementApiProcessor.java
- cloudwatch/deployment/src/main/java/io/quarkiverse/amazon/cloudwatch/deployment/CloudWatchProcessor.java
- cloudwatchlogs/deployment/src/main/java/io/quarkiverse/amazon/cloudwatch/deployment/CloudWatchLogsProcessor.java
- cognito-user-pools/deployment/src/main/java/io/quarkiverse/amazon/cognitouserpools/deployment/CognitoUserPoolsProcessor.java
- dynamodb-enhanced/deployment/src/main/java/io/quarkiverse/amazon/dynamodb/enhanced/deployment/DynamodbEnhancedProcessor.java
- dynamodb/deployment/src/main/java/io/quarkiverse/amazon/dynamodb/deployment/DynamodbProcessor.java
- ecr/deployment/src/main/java/io/quarkiverse/amazon/ecr/deployment/EcrProcessor.java
- eventbridge/deployment/src/main/java/io/quarkiverse/amazon/eventbridge/deployment/EventBridgeProcessor.java
- iam/deployment/src/main/java/io/quarkiverse/amazon/iam/deployment/IamProcessor.java
- inspector/deployment/src/main/java/io/quarkiverse/amazon/inspector/deployment/InspectorProcessor.java
- inspector2/deployment/src/main/java/io/quarkiverse/amazon/inspector2/deployment/Inspector2Processor.java
- kinesis/deployment/src/main/java/io/quarkiverse/amazon/kinesis/deployment/KinesisProcessor.java
- kms/deployment/src/main/java/io/quarkiverse/amazon/kms/deployment/KmsProcessor.java
- lambda/deployment/src/main/java/io/quarkiverse/amazon/lambda/deployment/LambdaProcessor.java
- paymentcryptography/deployment/src/main/java/io/quarkiverse/amazon/paymentcryptography/deployment/PaymentCryptographyProcessor.java
- paymentcryptographydata/deployment/src/main/java/io/quarkiverse/amazon/paymentcryptographydata/deployment/PaymentCryptographyDataProcessor.java
- s3-transfer-manager/deployment/src/main/java/io/quarkiverse/amazon/s3/deployment/S3TransferManagerProcessor.java
- s3/deployment/src/main/java/io/quarkiverse/amazon/s3/deployment/S3Processor.java
- secretsmanager/deployment/src/main/java/io/quarkiverse/amazon/secretsmanager/deployment/SecretsManagerProcessor.java
- ses/deployment/src/main/java/io/quarkiverse/amazon/ses/deployment/SesProcessor.java
- sfn/deployment/src/main/java/io/quarkiverse/amazon/sfn/deployment/SfnProcessor.java
- sns/deployment/src/main/java/io/quarkiverse/amazon/sns/deployment/SnsProcessor.java
- sqs/deployment/src/main/java/io/quarkiverse/amazon/sqs/deployment/SqsProcessor.java
- ssm/deployment/src/main/java/io/quarkiverse/amazon/ssm/deployment/SsmProcessor.java
- sts/deployment/src/main/java/io/quarkiverse/amazon/sts/deployment/StsProcessor.java
> fix: rename features to avoid collapsing with amazon-lambda

- dynamodb-enhanced/deployment/src/main/java/io/quarkiverse/amazon/dynamodb/enhanced/deployment/DynamodbEnhancedDbTableProcessor.java
- dynamodb-enhanced/deployment/src/test/java/io/quarkiverse/amazon/dynamodb/enhanced/deployment/DynamoDBEnhancedDbTableConstructorInjection.java
- dynamodb-enhanced/deployment/src/test/java/io/quarkiverse/amazon/dynamodb/enhanced/deployment/DynamoDbEnhancedDbTableTest.java
- dynamodb-enhanced/runtime/src/main/java/io/quarkiverse/amazon/dynamodb/enhanced/runtime/NamedDynamoDbTable.java
> feat: enable constructor injection of  NamedDynamoDbTable

- README.md
@scrocquesel I missed this in my previous PR.
> add elastic load balancing to service list

- common/runtime/src/main/java/io/quarkiverse/amazon/common/runtime/OtelNewSubstitutions.java
- common/runtime/src/main/java/io/quarkiverse/amazon/common/runtime/OtelOldSubstitutions.java
> fix: fix graalvm otel substitutions when sqs/sns are absent

- common/deployment-devservices-spi/pom.xml
- common/deployment-devservices-spi/src/main/java/io/quarkiverse/amazon/common/deployment/spi/AbstractDevServicesLocalStackProcessor.java
- common/deployment/src/main/java/io/quarkiverse/amazon/common/deployment/DevServicesLocalStackProcessor.java
Enable use integrating other devservices with localstack using a network alias as determined in #1527
> Remove unused parameter and add network alias

- README.md
- bom/pom.xml
- devservices/pom.xml
- devservices/sesv2/pom.xml
- devservices/sesv2/src/main/java/io/quarkiverse/amazon/devservices/sesv2/SesV2DevServicesProcessor.java
- docs/modules/ROOT/pages/amazon-sesv2.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sesv2.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-sesv2_quarkus.sesv2.adoc
- integration-tests/pom.xml
- pom.xml
- sesv2/deployment/pom.xml
- sesv2/deployment/src/main/java/io/quarkiverse/amazon/sesv2/deployment/SesV2Processor.java
- sesv2/deployment/src/test/java/io/quarkiverse/amazon/sesv2/deployment/SesV2SyncClientFullConfigTest.java
- sesv2/deployment/src/test/resources/sync-urlconn-full-config.properties
- sesv2/pom.xml
- sesv2/runtime/pom.xml
- sesv2/runtime/src/main/java/io/quarkiverse/amazon/sesv2/runtime/SesV2BuildTimeConfig.java
- sesv2/runtime/src/main/java/io/quarkiverse/amazon/sesv2/runtime/SesV2Config.java
- sesv2/runtime/src/main/java/io/quarkiverse/amazon/sesv2/runtime/SesV2Recorder.java
- sesv2/runtime/src/main/resources/META-INF/quarkus-extension.yaml
> feat: add sesv2 extension

- integration-tests/src/main/java/io/quarkiverse/it/amazon/dynamodb/DynamodbProducer.java
- integration-tests/src/main/resources/application.properties
> docs: explain how to provide a customized client instance

- crt/deployment/src/main/java/io/quarkiverse/amazonservices/aws/crt/deployment/AwsCrtProcessor.java
- docs/modules/ROOT/pages/common-features.adoc
> fix: remove obsolete aws-crt native build steps

- docs/modules/ROOT/pages/amazon-sso.adoc
- docs/modules/ROOT/pages/amazon-ssooidc.adoc
- sso/deployment/src/main/java/io/quarkiverse/amazon/sso/deployment/SsoNativeProcessor.java
- ssooidc/deployment/src/main/java/io/quarkiverse/amazon/ssooidc/deployment/SsoOidcNativeProcessor.java
> fix: fix sso in native mode

- s3/runtime/src/main/java/io/quarkiverse/amazon/s3/runtime/S3CrtSubstitutions.java
This is a problem with recent GraalVM versions.
> Make sure nested substitutions are static

- common/deployment/src/main/java/io/quarkiverse/amazon/common/deployment/DevServicesLocalStackProcessor.java
> fix: honor launch-on-shared-network configuration

- bom/pom.xml
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/amazon-apigateway.adoc
- docs/modules/ROOT/pages/amazon-apigatewayv2.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-apigateway.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-apigateway_quarkus.apigateway.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-apigatewayv2.adoc
- docs/modules/ROOT/pages/includes/quarkus-amazon-apigatewayv2_quarkus.apigatewayv2.adoc
- services/apigateway/deployment/pom.xml
- services/apigateway/deployment/src/test/java/io/quarkiverse/amazon/apigateway/deployment/ApiGatewayManagementApiSyncClientFullConfigTest.java
- services/apigateway/deployment/src/test/resources/sync-urlconn-full-config.properties
- services/apigateway/pom.xml
- services/apigateway/runtime/pom.xml
- services/apigateway/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- services/apigateway/src/main/resources/codegen-resources/customization.config
- services/apigateway/src/main/resources/codegen-resources/service-2.json
- services/apigatewayv2/deployment/pom.xml
- services/apigatewayv2/deployment/src/test/java/io/quarkiverse/amazon/apigatewayv2/deployment/ApiGatewayManagementApiSyncClientFullConfigTest.java
- services/apigatewayv2/deployment/src/test/resources/sync-urlconn-full-config.properties
- services/apigatewayv2/pom.xml
- services/apigatewayv2/runtime/pom.xml
- services/apigatewayv2/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- services/apigatewayv2/src/main/resources/codegen-resources/customization.config
- services/apigatewayv2/src/main/resources/codegen-resources/service-2.json
- services/pom.xml
> feat: add apigateway and apigatewayv2  extensions
