common/deployment/src/main/java/io/quarkus/amazon/common/deployment/AbstractAmazonServiceProcessor.java

Previously the early out meant that presigners were not available when one of the related clients are not injected. Fixed by taking the presigner into account before early exit.
Fixes #63.
This should probably include a test but to test it we'd need to replicate the `integration-test` module into a new module to test this specific case. It's been verified locally.

Skipping client processing now includes a check for presigners

---

common/runtime/src/main/java/io/quarkus/amazon/common/runtime/NettyHttpClientConfig.java
docs/modules/ROOT/pages/includes/quarkus-amazon-dynamodb.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-iam.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-kms.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-s3.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-secretsmanager.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-ses.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-sns.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-sqs.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-ssm.adoc
dynamodb/runtime/src/main/java/io/quarkus/amazon/dynamodb/runtime/DynamodbRecorder.java
iam/runtime/src/main/java/io/quarkus/amazon/iam/runtime/IamRecorder.java
kms/runtime/src/main/java/io/quarkus/amazon/kms/runtime/KmsRecorder.java
s3/runtime/src/main/java/io/quarkus/amazon/s3/runtime/S3Recorder.java
secretsmanager/runtime/src/main/java/io/quarkus/amazon/secretsmanager/runtime/SecretsManagerRecorder.java
sns/runtime/src/main/java/io/quarkus/amazon/sns/runtime/SnsRecorder.java
sqs/runtime/src/main/java/io/quarkus/amazon/sqs/runtime/SqsRecorder.java
ssm/runtime/src/main/java/io/quarkus/amazon/ssm/runtime/SsmRecorder.java

This PR introduces a new config option available to all the AWS extensions, making it possible to disable the default 50 thread pool described here: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/asynchronous.html#advanced-operations
(replaces #104)

add ability to disable thread pool used to complete futures in async clients

---

README.md
bom/pom.xml
cognito-user-pools/deployment/pom.xml
cognito-user-pools/deployment/src/main/java/io/quarkus/amazon/cognitouserpools/deployment/CognitoUserPoolsProcessor.java
cognito-user-pools/deployment/src/test/java/io/quarkus/amazon/cognitouserpools/deployment/CognitoUserPoolsBrokenEndpointConfigTest.java
cognito-user-pools/deployment/src/test/java/io/quarkus/amazon/cognitouserpools/deployment/CognitoUserPoolsSyncClientFullConfigTest.java
cognito-user-pools/deployment/src/test/resources/broken-endpoint-config.properties
cognito-user-pools/deployment/src/test/resources/full-config.properties
cognito-user-pools/pom.xml
cognito-user-pools/runtime/pom.xml
cognito-user-pools/runtime/src/main/java/io/quarkus/amazon/cognitouserpools/runtime/CognitoUserPoolsBuildTimeConfig.java
cognito-user-pools/runtime/src/main/java/io/quarkus/amazon/cognitouserpools/runtime/CognitoUserPoolsClientProducer.java
cognito-user-pools/runtime/src/main/java/io/quarkus/amazon/cognitouserpools/runtime/CognitoUserPoolsConfig.java
cognito-user-pools/runtime/src/main/java/io/quarkus/amazon/cognitouserpools/runtime/CognitoUserPoolsRecorder.java
cognito-user-pools/runtime/src/main/resources/META-INF/quarkus-extension.yaml
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/amazon-cognitouserpools.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-cognitouserpools.adoc
docs/pom.xml
integration-tests/pom.xml
integration-tests/src/main/java/io/quarkus/it/amazon/cognitouserpools/CognitoUserPoolsResource.java
integration-tests/src/main/resources/application.properties
integration-tests/src/test/java/io/quarkus/it/amazon/AmazonCognitoUserPoolsITCase.java
integration-tests/src/test/java/io/quarkus/it/amazon/AmazonCognitoUserPoolsTest.java
pom.xml

Hi, I have the intention to add support for Cognito Identity Provider API clients to this set of extensions. I am using Quarkus on the current project and in the near future I will implement user management, which we store in the Cognito User Pool.
My proposed implementation of the extension for Cognito User Pools I did by analogy with the current implementation of the extension for SQS.
I have successfully tested the injection and configuration of synchronous and asynchronous clients. And build a native image with a new extension. I checked the steps from the documentation locally, except for generating a project with the extension connected.
I have now implemented the following:
- Synchronous and asynchronous client configuration
- Provider for synchronous and asynchronous client
- Two …

Add Cognito User Pools clients

---

common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AbstractAmazonClientTransportRecorder.java
common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AmazonClientApacheTransportRecorder.java
common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AmazonClientNettyTransportRecorder.java
common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AmazonClientUrlConnectionTransportRecorder.java
common/runtime/src/main/java/io/quarkus/amazon/common/runtime/TlsKeyManagersProviderConfig.java
common/runtime/src/main/java/io/quarkus/amazon/common/runtime/TlsTrustManagersProviderConfig.java

Closes #237
Config provides a default value so a provider is always provided and returning Optional<> seems no more needed.
I fix some typos but don't know how to update the doc

fix: honor tls config when not setting file-store property

---

common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AmazonClientApacheTransportRecorder.java
common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AmazonClientNettyTransportRecorder.java
common/runtime/src/main/java/io/quarkus/amazon/common/runtime/NettyHttpClientConfig.java
common/runtime/src/main/java/io/quarkus/amazon/common/runtime/SyncHttpClientConfig.java
docs/modules/ROOT/pages/includes/quarkus-amazon-cognitouserpools.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-dynamodb.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-iam.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-kms.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-s3.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-secretsmanager.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-ses.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-sns.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-sqs.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-ssm.adoc
dynamodb/deployment/src/test/resources/async-full-config.properties
dynamodb/deployment/src/test/resources/sync-apache-full-config.properties

Refs: https://github.com/quarkiverse/quarkus-amazon-services/issues/116
TCP KeepAlive is currently supported for apache and netty only.
For apache, I set the param in the apache specific conf.
For netty, its the only async implementation, so its on the async conf directly.

Add support for TCP Keep-Alive

---

common/runtime/src/main/java/io/quarkus/amazon/common/runtime/LocalStackDevServicesBuildTimeConfig.java
docs/modules/ROOT/pages/amazon-kms.adoc
docs/modules/ROOT/pages/amazon-s3.adoc
docs/modules/ROOT/pages/amazon-secretsmanager.adoc
docs/modules/ROOT/pages/amazon-ses.adoc
docs/modules/ROOT/pages/amazon-sns.adoc
docs/modules/ROOT/pages/amazon-sqs.adoc
docs/modules/ROOT/pages/amazon-ssm.adoc
docs/modules/ROOT/pages/dev-services.adoc
integration-tests/src/main/resources/application.properties
s3/deployment/src/test/java/io/quarkus/amazon/s3/deployment/S3DevServicesTest.java

Currently, the default container image version used for localstack is `latest`. This causes unexpected issues every now and then. To avoid such issues, pinning the version is required.
Few integration tests kept failing with localstack versions 1.3.1 down till 1.0.4. These integration tests were related to SSM. As far as I understood (not an SSM expert), those failures looked like issues on the localstack side. Also, if that is indeed an issue on our end, then we can pick that work in another PR.

Pin localstack image version

---

common/deployment/src/main/java/io/quarkus/amazon/common/deployment/DevServicesLocalStackProcessor.java

Using a private registry to bypass docker hub rate limits currently fails when using this extension.
Exception
```
java.lang.IllegalStateException: Failed to verify that image '<private-registry>/localstack/localstack:1.3.1' is a compatible substitute for 'localstack/localstack'. This generally means that you are trying to use an image that Testcontainers has not been designed to use. If this is deliberate, and if you are confident that the image is compatible, you should declare compatibility in code using the `asCompatibleSubstituteFor` method.
```

Declare compatibility for localstack image substitute

---

common/runtime/src/main/java/io/quarkus/amazon/common/runtime/LocalStackDevServicesBuildTimeConfig.java
docs/modules/ROOT/pages/amazon-kms.adoc
docs/modules/ROOT/pages/amazon-s3.adoc
docs/modules/ROOT/pages/amazon-secretsmanager.adoc
docs/modules/ROOT/pages/amazon-ses.adoc
docs/modules/ROOT/pages/amazon-sns.adoc
docs/modules/ROOT/pages/amazon-sqs.adoc
docs/modules/ROOT/pages/amazon-ssm.adoc
docs/modules/ROOT/pages/dev-services.adoc
integration-tests/src/main/resources/application.properties
s3/deployment/src/test/java/io/quarkus/amazon/s3/deployment/S3DevServicesTest.java

Change localstack port to 4566 (new default). See examples they provided: https://docs.localstack.cloud/user-guide/aws/sqs/
Align it with quarkusio/quarkus-quickstarts PR which also use version 1.4.0 and container + local port 4566

Bump localstack version to 1.4.0.

---

bom/pom.xml
common/deployment-apache-client-internal/pom.xml
common/deployment-netty-client-internal/pom.xml
common/pom.xml
common/runtime-apache-client-internal/pom.xml
common/runtime-netty-client-internal/pom.xml
common/runtime/pom.xml
docs/modules/ROOT/pages/amazon-cognitouserpools.adoc
docs/modules/ROOT/pages/amazon-dynamodb.adoc
docs/modules/ROOT/pages/amazon-kms.adoc
docs/modules/ROOT/pages/amazon-s3.adoc
docs/modules/ROOT/pages/amazon-secretsmanager.adoc
docs/modules/ROOT/pages/amazon-ses.adoc
docs/modules/ROOT/pages/amazon-sns.adoc
docs/modules/ROOT/pages/amazon-sqs.adoc
docs/modules/ROOT/pages/amazon-ssm.adoc
docs/modules/ROOT/pages/amazon-sts.adoc
integration-tests/pom.xml
integration-tests/src/main/resources/application.properties

This adds conditional extension dependencies to the common module, which allows for the automatic inclusion of the required Quarkus extensions for Netty and Apache clients.
With this change, developers won't need to manually add the Quarkus extensions for Netty and Apache, since they will be automatically included based on the project's use of the HTTP client implementation dependencies.

Add conditional extension dependencies for Apache and Netty

---

common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AbstractAmazonClientTransportRecorder.java

Fixed the validateFileStore part were filestore.password is checked instead of filestore.path.
I came across this while deploying Nessie (https://github.com/projectnessie/nessie) with a DynamoDB backend.

Fixed filestore.path check in validateFileStore

---

cognito-user-pools/deployment/src/main/java/io/quarkus/amazon/cognitouserpools/deployment/CognitoUserPoolsProcessor.java
cognito-user-pools/runtime/src/main/java/io/quarkus/amazon/cognitouserpools/runtime/CognitoUserPoolsRecorder.java
common/deployment/src/main/java/io/quarkus/amazon/common/deployment/AbstractAmazonServiceProcessor.java
common/runtime/src/main/java/io/quarkus/amazon/common/runtime/AmazonClientRecorder.java
dynamodb/deployment/src/main/java/io/quarkus/amazon/dynamodb/deployment/DynamodbProcessor.java
dynamodb/runtime/src/main/java/io/quarkus/amazon/dynamodb/runtime/DynamodbRecorder.java
iam/deployment/src/main/java/io/quarkus/amazon/iam/deployment/IamProcessor.java
iam/runtime/src/main/java/io/quarkus/amazon/iam/runtime/IamRecorder.java
kms/deployment/src/main/java/io/quarkus/amazon/kms/deployment/KmsProcessor.java
kms/runtime/src/main/java/io/quarkus/amazon/kms/runtime/KmsRecorder.java
s3/deployment/src/main/java/io/quarkus/amazon/s3/deployment/S3Processor.java
s3/runtime/src/main/java/io/quarkus/amazon/s3/runtime/S3Recorder.java
secretsmanager/deployment/src/main/java/io/quarkus/amazon/secretsmanager/deployment/SecretsManagerProcessor.java
secretsmanager/runtime/src/main/java/io/quarkus/amazon/secretsmanager/runtime/SecretsManagerRecorder.java
ses/deployment/src/main/java/io/quarkus/amazon/ses/deployment/SesProcessor.java
ses/runtime/src/main/java/io/quarkus/amazon/ses/runtime/SesRecorder.java
sns/deployment/src/main/java/io/quarkus/amazon/sns/deployment/SnsProcessor.java
sns/runtime/src/main/java/io/quarkus/amazon/sns/runtime/SnsRecorder.java
sqs/deployment/src/main/java/io/quarkus/amazon/sqs/deployment/SqsProcessor.java
sqs/runtime/src/main/java/io/quarkus/amazon/sqs/runtime/SqsRecorder.java
ssm/deployment/src/main/java/io/quarkus/amazon/ssm/deployment/SsmProcessor.java
ssm/runtime/src/main/java/io/quarkus/amazon/ssm/runtime/SsmRecorder.java
sts/deployment/src/main/java/io/quarkus/amazon/sts/deployment/StsProcessor.java
sts/runtime/src/main/java/io/quarkus/amazon/sts/runtime/StsRecorder.java

By default, AWS SDK creates multiple ThreadPools per client instance, one for future completion executor and one for schedule executor service. This PR replaces this behavior and use quarkus default thread pool for all client instances and ThreadPool usages.

feat: use quarkus default thread pool

---

dynamodb-enhanced/runtime/pom.xml
sts/runtime/pom.xml

Caused by https://github.com/quarkusio/quarkus/pull/34145

fix: move to sdk:graal-sdk over nativeimage:svm

---

docs/modules/ROOT/pages/amazon-dynamodb.adoc
docs/modules/ROOT/pages/amazon-sns.adoc
docs/modules/ROOT/pages/amazon-sqs.adoc

Proof of all warnings gone:
Proof of warnings before this PR:
Note: I fixed only main branch because I noticed in other projects that maintainers want to do downmerge manually.

Fix asciidoc warnings by using proper links

---

devservices/cognito-user-pools/src/main/java/io/quarkus/amazon/devservices/cognitouserpools/CognitoUserPoolsDevServicesProcessor.java

Copied implementation from base class used by other services:
https://github.com/quarkiverse/quarkus-amazon-services/blob/4ac8b51fa5395994accea1a4230c57b5d597b18d/common/deployment-devservices-spi/src/main/java/io/quarkus/amazon/common/deployment/spi/AbstractDevServicesLocalStackProcessor.java#L27-L33
Addresses concern raised here: https://github.com/quarkusio/quarkus/issues/34801#issuecomment-1669665084

support explicitly disabling dev services for cognito user pools

---

README.md

docs: separate docs for for 2.4 branch

---

common/runtime/src/main/java/io/quarkus/amazon/common/runtime/LocalStackDevServicesBuildTimeConfig.java
docs/modules/ROOT/pages/amazon-kms.adoc
docs/modules/ROOT/pages/amazon-s3.adoc
docs/modules/ROOT/pages/amazon-secretsmanager.adoc
docs/modules/ROOT/pages/amazon-ses.adoc
docs/modules/ROOT/pages/amazon-sns.adoc
docs/modules/ROOT/pages/amazon-sqs.adoc
docs/modules/ROOT/pages/amazon-ssm.adoc
docs/modules/ROOT/pages/amazon-sts.adoc
docs/modules/ROOT/pages/dev-services.adoc
docs/modules/ROOT/pages/includes/quarkus-aws-devservices-localstack-local-stack-dev-services-build-time-config.adoc
integration-tests/src/main/resources/application.properties
pom.xml
s3/deployment/src/test/java/io/quarkus/amazon/s3/deployment/S3DevServicesTest.java
sqs/deployment/src/test/java/io/quarkus/amazon/sqs/deployment/SqsDevServicesWithoutQueueTest.java

Starting from AWS SDK version [2.21.19](https://github.com/aws/aws-sdk-java/releases/tag/2.21.19), AWS updated the protocol in the SQS API, and it is not compatible with versions of LocalStack lower than 3.0.1.

feat: bump default localstack from 2.3.0 to 3.0.1

---

common/deployment/src/main/java/io/quarkus/amazon/common/deployment/DevServicesLocalStackProcessor.java
common/runtime/src/main/java/io/quarkus/amazon/common/runtime/LocalStackDevServicesBuildTimeConfig.java
docs/modules/ROOT/pages/includes/quarkus-aws-devservices-localstack-local-stack-dev-services-build-time-config.adoc

This update includes the ability to set an optional fixed port for LocalStack in Quarkus AWS DevServices.
closes https://github.com/quarkiverse/quarkus-amazon-services/issues/794

feat: Devservice localstack port

---

common/runtime-apache-client-internal/src/main/resources/META-INF/quarkus-extension.yaml
common/runtime-crt-client-internal/src/main/resources/META-INF/quarkus-extension.yaml
common/runtime-netty-client-internal/src/main/resources/META-INF/quarkus-extension.yaml
common/runtime-opentelemetry-internal/src/main/resources/META-INF/quarkus-extension.yaml

I notice that several extensions in this project are named as 'internal,' because they're wrappers for other extensions. 
There's an 'unlisted' metadata key that can be used to mark this kind of extension. It stops the extension from being listed in https://code.quarkus.io, and also stops it from showing in https://extensions.quarkus.io unless someone explicitly searches for it. (In this screencap, the left-most extension has been marked as internal, and is only showing because of the specific search.)
By the way, this is definitely a 'no accusation' PR - we don't really document `unlisted`, so there's no reason these extensions should have known to use it! There's also no harm in the `unlisted` key not being there, just a little bit of clutter.

Add metadata to mark internal extensions as unlisted

---

docs/modules/ROOT/pages/amazon-dynamodb.adoc

The mentioned issue was resolved and AWS SDK 2 is in GA. I don't think the warning is applicable anymore.

docs: remove obsolete warning

---

s3/deployment/src/main/java/io/quarkus/amazon/s3/deployment/S3CrtProcessor.java

Fix #1335 
The discover step was initially looking for all injection points, but during the filtering process, it incorrectly filtered by `S3CrtAsyncClient.class`. The injection point, however, expects to use `S3AsyncClient.class`.
```java
@Inject
@S3Crt
S3AsyncClient s3AsyncClient;
```

fix: S3Crt async client injection issue

---

devservices/cognito-user-pools/src/main/java/io/quarkus/amazon/devservices/cognitouserpools/CognitoUserPoolsDevServicesProcessor.java

Fixes https://github.com/quarkiverse/quarkus-amazon-services/issues/1398
Passes container properties to the moto container.  
To achieve the reproducible user pool ids you need to define a property:
`quarkus.aws.devservices.moto.container-properties.MOTO_COGNITO_IDP_USER_POOL_ID_STRATEGY=HASH`

feat: pass container properties to moto container

---

docs/modules/ROOT/pages/includes/attributes.adoc
pom.xml

This is needed, otherwise Maven will just use the latest version released in Maven Central - which might not be compatible with the model generated by the quarkus-extension-processor.

Enforce quarkus-config-doc-maven-plugin version

---

README.md
apigatewaymanagementapi/deployment/pom.xml
apigatewaymanagementapi/deployment/src/main/java/io/quarkiverse/amazon/apigatewaymanagementapi/deployment/ApiGatewayManagementApiProcessor.java
apigatewaymanagementapi/deployment/src/test/java/io/quarkiverse/amazon/apigatewaymanagementapi/deployment/ApiGatewayManagementApiSyncClientFullConfigTest.java
apigatewaymanagementapi/deployment/src/test/resources/sync-urlconn-full-config.properties
apigatewaymanagementapi/pom.xml
apigatewaymanagementapi/runtime/pom.xml
apigatewaymanagementapi/runtime/src/main/java/io/quarkiverse/amazon/apigatewaymanagementapi/runtime/ApiGatewayManagementApiBuildTimeConfig.java
apigatewaymanagementapi/runtime/src/main/java/io/quarkiverse/amazon/apigatewaymanagementapi/runtime/ApiGatewayManagementApiConfig.java
apigatewaymanagementapi/runtime/src/main/java/io/quarkiverse/amazon/apigatewaymanagementapi/runtime/ApiGatewayManagementApiRecorder.java
apigatewaymanagementapi/runtime/src/main/resources/META-INF/quarkus-extension.yaml
bom/pom.xml
docs/modules/ROOT/pages/amazon-apigatewaymanagementapi.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-apigatewaymanagementapi.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-apigatewaymanagementapi_quarkus.apigatewaymanagementapi.adoc
pom.xml

feat: add api gateway management api extension

---

README.md
bom/pom.xml
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/amazon-neptune.adoc
docs/modules/ROOT/pages/includes/attributes.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-neptune.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-neptune_quarkus.neptune.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-paymentcryptography_quarkus.adoc
docs/modules/ROOT/pages/includes/quarkus-amazon-paymentcryptographydata_quarkus.adoc
integration-tests/src/main/java/io/quarkiverse/it/amazon/acm/AcmResource.java
integration-tests/src/test/java/io/quarkiverse/it/amazon/AmazonAcmTest.java
neptune/deployment/pom.xml
neptune/deployment/src/main/java/io/quarkiverse/amazon/neptune/deployment/NeptuneProcessor.java
neptune/deployment/src/test/java/io/quarkiverse/amazon/neptune/deployment/NeptuneSyncClientFullConfigTest.java
neptune/deployment/src/test/resources/sync-urlconn-full-config.properties
neptune/pom.xml
neptune/runtime/pom.xml
neptune/runtime/src/main/java/io/quarkiverse/amazon/neptune/runtime/NeptuneBuildTimeConfig.java
neptune/runtime/src/main/java/io/quarkiverse/amazon/neptune/runtime/NeptuneConfig.java
neptune/runtime/src/main/java/io/quarkiverse/amazon/neptune/runtime/NeptuneRecorder.java
neptune/runtime/src/main/resources/META-INF/quarkus-extension.yaml
pom.xml

feat: add neptune extension

---

devservices/cognito-user-pools/src/main/java/io/quarkiverse/amazon/devservices/cognitouserpools/MotoContainer.java

Hello, currently `getmoto` gets its image from docker hub. Unfortunately I cannot rely on it and was instead trying to configure to use the [other official image](https://docs.getmoto.org/en/latest/docs/server_mode.html#run-using-docker) which is hosted on Github.
But while docker image is tagged as `motoserver/moto`, the github official image is tagged as `getmoto/motoserver`.
MotoContainer is using `assertCompatibleWith` which will fails namespace is different, unlike other docker images, for example [localstack](https://github.com/quarkiverse/quarkus-amazon-services/blob/564fa050b05e978517cf9c24f74134f1e1989a2b/common/deployment/src/main/java/io/quarkiverse/amazon/common/deployment/DevServicesLocalStackProcessor.java#L260), which use `asCompatibleSubstituteFor`, allowing different …

feat: add support for custom moto docker image

---

dynamodb-enhanced/deployment/src/test/java/io/quarkiverse/amazon/dynamodb/enhanced/deployment/DynamoDbEnhancedClientTest.java
dynamodb-enhanced/deployment/src/test/java/io/quarkiverse/amazon/dynamodb/enhanced/deployment/DynamoDbEnhancedDbTableTest.java

I am having trouble compiling these tests in my environment, because the legacy JUnit API is not found on the compile time classpath. This change updates the test to use the JUnit Jupiter API, which is consistent with the rest of the tests in the project and resolves this issue.

♻️ Prefer JUnit Jupiter API

---

s3/runtime/src/main/java/io/quarkiverse/amazon/s3/runtime/S3Recorder.java

Fixes https://github.com/quarkiverse/quarkus-amazon-services/issues/1639 by reverting changes made to `S3Recorder.java` on https://github.com/quarkiverse/quarkus-amazon-services/pull/1518

Apply All S3Client configurations to S3Presigner

---

common/runtime/src/main/java/io/quarkiverse/amazon/common/runtime/CrtSubstitutions.java

Closes #1659 
on Delete_DefaultAwsCrtV4aHttpSigner requires an additional `static` modifier to the class for graalvm to build the native image
As all the inner classes declared in `CrtSubstitutions` are marked as `static` (and this one not), it should be marked as static and should not be breaking other code.
Ran tests after the change using the follow command:
```shell
mvn surefire-report:report -Daggregate=true -Dmaven.compiler.source=24 -Dmaven.compiler.target=24
```
But it seems hard to test graalvm build classes.

fix(common/runtime): missing static modifier

---

bom-internal/pom.xml

Because this is missing, the 3.6.0 release failed in  https://github.com/quarkiverse/quarkiverse-release/actions/runs/14974800965/job/42064280764

Add `<name>` to bom-internal

---

codegen/src/main/java/io/quarkiverse/amazon/codegen/poet/runtime/RecorderClass.java
codegen/src/test/resources/io/quarkiverse/amazon/codegen/poet/runtime/test-recorder-class.java
cognito-user-pools/runtime/src/main/java/io/quarkiverse/amazon/cognitouserpools/runtime/CognitoUserPoolsRecorder.java
common/deployment-spi/src/main/java/io/quarkiverse/amazon/common/deployment/AmazonClientExtensionBuildItem.java
common/deployment/src/main/java/io/quarkiverse/amazon/common/deployment/AmazonClientExtensionsProcessor.java
common/runtime-spi/src/main/java/io/quarkiverse/amazon/common/runtime/AmazonClientRecorder.java
common/runtime/src/main/java/io/quarkiverse/amazon/common/runtime/AmazonClientCommonRecorder.java
s3/runtime/src/main/java/io/quarkiverse/amazon/s3/runtime/S3CrtRecorder.java
s3/runtime/src/main/java/io/quarkiverse/amazon/s3/runtime/S3Recorder.java
scheduler/runtime/src/main/java/io/quarkiverse/amazon/scheduler/runtime/SchedulerRecorder.java
sqs/runtime/src/main/java/io/quarkiverse/amazon/sqs/runtime/SqsRecorder.java

With https://github.com/quarkusio/quarkus/pull/48500, we will disallow the injection of Runtime configuration objects during deployment. The recommended way is to inject it directly into the Recorder, wrapped in a `RuntimeValue`.

Do not use Runtime configuration during deployment
